# Generated by Django 5.1.5 on 2025-04-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResponseForm',
            new_name='Response',
        ),
    ]
